baseurl = "http://keruru.net/"
title =  "Keruruのブログ "
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "rokkaku"

[taxonomies]
  tag = "tags"
  archive = "archives"

[markup]
  [highlight]
    codeFences = false
    guessSyntax = false
    noClasses = false

[params]
  limitNumberOfLatests = 5
  logoHtml = "<figure><img src=\"/img/avatar.jpg\" width=\"80%\" /></figure>"
  amazonJpAffiliate = "kerurudigit-22"
  description = "けるるの日常を綴る..."
  github = "1484"
  twitter = "keruru"
  copyrightHtml = "Copyright &copy; Keruru All Rights Reserved. 2016&ndash;2021"
  rss = true
  styles = ["/css/custom.css", ""]

  [ga]
  trackingId = "UA-2733118-1"
