baseurl = "http://keruru.net/"
title =  "けるるmemo "
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "primer"
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true
copyright = "Copyright &copy; Keruru All Rights Reserved. 2016&ndash;2022"
googleAnalytics = "G-NKS2GSR0KZ"
paginate = 5


[taxonomies]
  tag = "tags"
  archive = "archives"
  category = 'categories'

[markup]
  [highlight]
    codeFences = false
    guessSyntax = false
    noClasses = false

[params]
  limitNumberOfLatests = 5
  logoHtml = "<figure><img src=\"/img/avatar.jpg\" width=\"80%\" /></figure>"
  amazonJpAffiliate = "kerurudigit-22"
  description = "けるるの日常を綴る..."
  github = "1484"
  twitter = "keruru"
  useTwitterCard = true
  copyrightHtml = "Copyright &copy; Keruru All Rights Reserved. 2016&ndash;2021"
  rss = true
  styles = ["/css/custom.css", ""]
  showFooterCredits = true


  [ga]
  # trackingId = "UA-2733118-1"
  trackingId = "G-NKS2GSR0KZ"
  
