baseURL = "https://keruru.net"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Keruru Digit"
theme = "dream"
copyright = '(C)Keruru. All Rights Reserved'
googleAnalytics = ""
disqusShortname = "keruru"
enableRobotsTXT = true
hasCJKLanguage = true
pygmentsCodeFences = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  #background = "black"
  backgroundImage = "/img/hawaii.jpg"
  linkColor = "seagreen"

  author = "keruru"
  description = "けるるの日常を綴る..."
  avatar= "/img/avatar.jpg"
  motto = "けるるの日常を綴る..."
  
  email = "takeru@1974.jp"
  twitter = "keruru"
  facebook = "takeru.ishibashi"
  instagram = "keruru03"
  #linkedin = ""
  github = "1484"
  #stackoverflow = ""
  #codepen = ""

  rss = true

  siteStartYear = 2006

  #favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  backgroundDark = "black"
  backgroundImageDark = "/img/hawaii_d.jpg"
  darkNav = true
  dark404Button = true

  enableGitInfo = true

  showSummaryCoverInPost = true

  customCSS = ["/css/custom.css"]

  categoriesLimitInHeader = 7
  # headerBottomText = ""

  enableSearch = true

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

[outputs]
  home = ["HTML", "RSS", "JSON"]

