version: '3'
services: 
    hugo:
        image: klakegg/hugo:0.82.0-ubuntu
        volumes:
            - ".:/src"
        entrypoint: bash
        ports:
            - "1313:1313"
        tty: true
        working_dir: /src

