version: '3'
services: 
    hugo:
        image: klakegg/hugo:0.101.0-ext-ubuntu
        #        platform: linux/x86_64
        volumes:
            - ".:/src"
        entrypoint: bash
        ports:
            - "1313:1313"
        tty: true
        working_dir: /src
        command: hugo server -w -D --disableFastRender --buildFuture

